apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app-config.yaml
  - app-secrets.yaml
  - postgres.yaml
  - redis.yaml
  - redpanda.yaml
  - zookeeper.yaml
  - clickhouse.yaml
  - seaweedfs.yaml
  - browserless.yaml
  - temporal.yaml
  - posthog-app.yaml
  - ingress-routes.yaml
