# Generated by Django 4.2.29 on 2026-04-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0031_ticket_cc_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="identity_verified",
            field=models.BooleanField(default=False),
        ),
    ]
